// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
}

type UserInfoResp struct {
}

type CategoryReq struct {
	Name     string `json:"name"`
	Status   int    `json:"status"`
	Page     int64  `json:"page"`
	PageSize int64  `json:"pagesize"`
}

type CommonResp struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data CategoryResp `json:"data"`
}

type CategoryResp struct {
	Id                 int64             `json:"id"`
	Pid                int64             `json:"pid"`
	Name               string            `json:"name"`
	Status             string            `json:"status"`
	Remark             string            `json:"remark"`
	Get_second_service []CategoryRespSon `json:"get_second_service"`
}

type PageResp struct {
	Current_page int64          `json:"current_page"`
	Page_size    int64          `json:"page_size"`
	Total_page   int64          `json:"total_page"`
	Total_item   int64          `json:"total_item"`
	List         []CategoryResp `json:"list"`
}

type CategoryRespSon struct {
	Id     int64  `json:"id"`
	Pid    int64  `json:"pid"`
	Name   string `json:"name"`
	Status string `json:"status"`
	Remark string `json:"remark"`
}

type CommonReponse struct {
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type SearchReq struct {
	Name string `json:"name"`
}

type SearchReply struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}

type PublishingListReq struct {
}

type PublishingListResp struct {
}
