// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	category "gov-cms/app/internal/handler/category"
	ping "gov-cms/app/internal/handler/ping"
	publishing "gov-cms/app/internal/handler/publishing"
	"gov-cms/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/search/ping",
				Handler: ping.PingHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/servicecategory/list",
				Handler: category.ServiceCategoryListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/publishing/publishing/list",
				Handler: publishing.PublishingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/data/list",
				Handler: publishing.ReturnDataListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
